(define (fast-mutli a b) 
  (define (double n) 
    (+ n n)) 
  (define (halve n) 
    (/ n 2)) 
  (define (even? n) 
    (= (remainder n 2) 0))
  (define (fast-mutli-iter a b n)
    (cond ((= b 0) n)
	  ((even? b) (fast-mutli-iter (double a) (halve b) n))
	  (else (fast-mutli-iter a (- b 1) (+ n a)))))
  (fast-mutli-iter a b 0))

(fast-mutli 1 1)
(fast-mutli 1 2)
(fast-mutli 2 3)
(fast-mutli 3 4)
